name: Go

on:
  push:
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ '1.19.x' ]
        module: [ 'pkg', 'cmd', 'gui' ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        working-directory: ${{ matrix.module }}
        run: go get -v -t -d ./...

      - name: Install fyne dependency packages
        if: ${{ matrix.module == 'gui' }}
        run: >
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq
          libgl1-mesa-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          xorg-dev

      - name: Test
        working-directory: ${{ matrix.module }}
        run: go test -v ./...
