name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.15.6'

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module: [ 'pkg', 'cmd', 'gui' ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ${{ matrix.module }}
        run: go get -v -t -d ./...

      - name: Install fyne dependency packages
        if: ${{ matrix.module == 'gui' }}
        run: >
          sudo apt-get install -y -qq &&
          sudo apt-get install -y -qq
          libgl1-mesa-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          xorg-dev

      - name: Test
        working-directory: ${{ matrix.module }}
        run: go test -v ./...


  package-gui:
    name: Package GUI
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [ 'linux', 'darwin', 'windows' ]
        arch: [ 'amd64' ]
        include:
          - platform: 'linux'
            arch: 'arm64'
          - platform: 'linux'
            arch: '386'

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup fyne-cross
        working-directory: build
        run: |
          go mod download
          go install github.com/fyne-io/fyne-cross

      - name: Vendor dependencies for GUI
        working-directory: gui
        run: |
          go mod vendor

      - name: Build fyne GUI
        working-directory: gui
        run: |
          fyne-cross "$MATRIX_PLATFORM" -arch="$MATRIX_ARCH" -output=situ-vault ./situ-vault
        env:
          MATRIX_PLATFORM: ${{ matrix.platform }}
          MATRIX_ARCH: ${{ matrix.arch }}

      - name: Create tar for GUI
        working-directory: gui
        # only needed for macos to keep the executable flag
        if: ${{ matrix.platform == 'darwin' }}
        run: |
          DIST_FOLDER="fyne-cross/dist/$MATRIX_PLATFORM-$MATRIX_ARCH"
          tar cfvz "$DIST_FOLDER/situ-vault.app.tar.gz" "$DIST_FOLDER/situ-vault.app"
        env:
          MATRIX_PLATFORM: ${{ matrix.platform }}
          MATRIX_ARCH: ${{ matrix.arch }}

      - name: Upload GUI dist
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('dist-gui-{0}-{1}', matrix.platform, matrix.arch) }}
          path: |
            gui/fyne-cross/dist/*/*.tar.gz
            gui/fyne-cross/dist/*/*.zip
          retention-days: 1
