name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
          stable: false

      - run: go version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies PKG
        working-directory: pkg
        run: go get -v -t -d ./...

      - name: Test PKG
        working-directory: pkg
        run: go test -v ./...

      - name: Get dependencies CMD
        working-directory: cmd
        run: go get -v -t -d ./...

      - name: Test CMD
        working-directory: cmd
        run: go test -v ./...
