name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module: [ 'pkg', 'cmd', 'gui' ]

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
          stable: false

      - run: go version

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ${{ matrix.module }}
        run: go get -v -t -d ./...

      - name: Install fyne dependency packages
        if: ${{ matrix.module == 'gui' }}
        run: >
          sudo apt-get install -y -qq &&
          sudo apt-get install -y -qq
          libgl1-mesa-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          xorg-dev

      - name: Test
        working-directory: ${{ matrix.module }}
        run: go test -v ./...

      - name: Setup fyne-cross
        working-directory: build
        if: ${{ matrix.module == 'gui' }}
        run: |
          go mod download
          go install github.com/fyne-io/fyne-cross

      - name: Build fyne GUI
        working-directory: ${{ matrix.module }}
        if: ${{ matrix.module == 'gui' }}
        run: |
          go mod vendor
          fyne-cross linux   -arch=amd64,arm64,386 -output=situ-vault-gui ./situ-vault
          fyne-cross darwin  -arch=amd64           -output=situ-vault-gui ./situ-vault
          fyne-cross windows -arch=amd64           -output=situ-vault-gui ./situ-vault

      - name: Upload GUI dist
        uses: actions/upload-artifact@v2
        if: ${{ matrix.module == 'gui' }}
        with:
          name: dist-gui
          path: gui/fyne-cross/dist/ # or path/to/artifact
          retention-days: 1
