name: Lint

on:
  push:
  pull_request:

env:
  GO_VERSION: '1.19.x'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        module: [ 'pkg', 'cmd', 'gui' ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: ${{ !contains(env.GO_VERSION, 'rc') }}

      - name: Install linters
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@v0.2.1

      - name: Install fyne dependency packages
        if: ${{ matrix.module == 'gui' }}
        run: >
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq
          libgl1-mesa-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
          xorg-dev

      - name: Check out code
        uses: actions/checkout@v3

      - name: Vet
        working-directory: ${{ matrix.module }}
        run: go vet -tags ci ./...

      - name: Goimports
        working-directory: ${{ matrix.module }}
        run: test -z $(goimports -e -d . | tee /dev/stderr)

      - name: Staticcheck
        working-directory: ${{ matrix.module }}
        run: staticcheck ./...
